version: 2.1
jobs:
  build:
    docker:
      - image: cimg/go:1.17
    steps:
      - checkout
      - setup_remote_docker
      - run: wget https://raw.githubusercontent.com/puki89/siap/main/Dockerfile
      - run: docker build -t cc:latest